## Customize Makefile settings for h2kg
##
## This file is generated by the AIMWORKS ontology release pipeline.
## It overrides ODK mirror/import rules for non-OBO sources used by H2KG.

EMMO_CORE_CACHE := ../../../cache/sources/emmo-core.ttl
EMMO_CORE_URL := https://w3id.org/emmo
EMMO_CORE_REQUIRED := true

.PHONY: mirror-emmo-core
.PRECIOUS: $(MIRRORDIR)/emmo-core.owl
mirror-emmo-core: | $(TMPDIR)
	@if [ -f $(EMMO_CORE_CACHE) ]; then \
		echo "Using local cache for emmo-core: $(EMMO_CORE_CACHE)"; \
		$(ROBOT) convert -i $(EMMO_CORE_CACHE) -o $(TMPDIR)/$@.owl; \
	elif [ -n "$(EMMO_CORE_URL)" ]; then \
		echo "Downloading emmo-core from $(EMMO_CORE_URL)"; \
		if curl -L "$(EMMO_CORE_URL)" -H "Accept: application/rdf+xml, application/owl+xml;q=0.95, text/turtle;q=0.9, text/plain;q=0.8, text/xml;q=0.8" --create-dirs -o $(TMPDIR)/emmo-core-download.owl --retry 4 --max-time 200 && $(ROBOT) convert -i $(TMPDIR)/emmo-core-download.owl -o $(TMPDIR)/$@.owl; then \
			true; \
		else \
			echo "Remote fetch failed for emmo-core; writing placeholder mirror for shadow-mode continuity."; \
			printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/emmo-core_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/emmo-core_import.owl>)' > $(TMPDIR)/$@.ofn; \
			$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
		fi; \
	elif [ "$(EMMO_CORE_REQUIRED)" = "true" ]; then \
		echo "Missing required cache or remote URL for emmo-core; writing placeholder mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/emmo-core_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/emmo-core_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	else \
		echo "Skipping optional source emmo-core; writing placeholder import mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/emmo-core_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/emmo-core_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	fi

$(IMPORTDIR)/emmo-core_import.owl: $(MIRRORDIR)/emmo-core.owl $(IMPORTDIR)/emmo-core_terms.txt $(IMPORTSEED) | all_robot_plugins
	@if [ ! -s $(IMPORTDIR)/emmo-core_terms.txt ]; then \
		echo "No configured terms for emmo-core; writing placeholder import module."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/emmo-core_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/emmo-core_import.owl>)' > $(IMPORTDIR)/emmo-core_import.ofn; \
		$(ROBOT) convert -i $(IMPORTDIR)/emmo-core_import.ofn -o $(IMPORTDIR)/emmo-core_import.owl; \
		rm -f $(IMPORTDIR)/emmo-core_import.ofn; \
	else \
		$(ROBOT) annotate --input $< --remove-annotations \
			 odk:normalize --add-source true \
			 extract --term-file $(IMPORTDIR)/emmo-core_terms.txt $(T_IMPORTSEED) \
			         --force true --copy-ontology-annotations true \
			         --individuals include \
			         --method BOT \
			 remove $(foreach p, $(ANNOTATION_PROPERTIES), --term $(p)) \
			        --term-file $(IMPORTDIR)/emmo-core_terms.txt $(T_IMPORTSEED) \
			        --select complement --select annotation-properties \
			 odk:normalize --base-iri http://purl.obolibrary.org/obo \
			               --subset-decls true --synonym-decls true \
			 repair --merge-axiom-annotations true \
			 $(ANNOTATE_CONVERT_FILE); \
	fi

EMMO_ELECTROCHEMISTRY_CACHE := ../../../cache/sources/emmo-electrochemistry.ttl
EMMO_ELECTROCHEMISTRY_URL := https://w3id.org/emmo/domain/electrochemistry
EMMO_ELECTROCHEMISTRY_REQUIRED := true

.PHONY: mirror-emmo-electrochemistry
.PRECIOUS: $(MIRRORDIR)/emmo-electrochemistry.owl
mirror-emmo-electrochemistry: | $(TMPDIR)
	@if [ -f $(EMMO_ELECTROCHEMISTRY_CACHE) ]; then \
		echo "Using local cache for emmo-electrochemistry: $(EMMO_ELECTROCHEMISTRY_CACHE)"; \
		$(ROBOT) convert -i $(EMMO_ELECTROCHEMISTRY_CACHE) -o $(TMPDIR)/$@.owl; \
	elif [ -n "$(EMMO_ELECTROCHEMISTRY_URL)" ]; then \
		echo "Downloading emmo-electrochemistry from $(EMMO_ELECTROCHEMISTRY_URL)"; \
		if curl -L "$(EMMO_ELECTROCHEMISTRY_URL)" -H "Accept: application/rdf+xml, application/owl+xml;q=0.95, text/turtle;q=0.9, text/plain;q=0.8, text/xml;q=0.8" --create-dirs -o $(TMPDIR)/emmo-electrochemistry-download.owl --retry 4 --max-time 200 && $(ROBOT) convert -i $(TMPDIR)/emmo-electrochemistry-download.owl -o $(TMPDIR)/$@.owl; then \
			true; \
		else \
			echo "Remote fetch failed for emmo-electrochemistry; writing placeholder mirror for shadow-mode continuity."; \
			printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/emmo-electrochemistry_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/emmo-electrochemistry_import.owl>)' > $(TMPDIR)/$@.ofn; \
			$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
		fi; \
	elif [ "$(EMMO_ELECTROCHEMISTRY_REQUIRED)" = "true" ]; then \
		echo "Missing required cache or remote URL for emmo-electrochemistry; writing placeholder mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/emmo-electrochemistry_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/emmo-electrochemistry_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	else \
		echo "Skipping optional source emmo-electrochemistry; writing placeholder import mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/emmo-electrochemistry_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/emmo-electrochemistry_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	fi

$(IMPORTDIR)/emmo-electrochemistry_import.owl: $(MIRRORDIR)/emmo-electrochemistry.owl $(IMPORTDIR)/emmo-electrochemistry_terms.txt $(IMPORTSEED) | all_robot_plugins
	@if [ ! -s $(IMPORTDIR)/emmo-electrochemistry_terms.txt ]; then \
		echo "No configured terms for emmo-electrochemistry; writing placeholder import module."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/emmo-electrochemistry_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/emmo-electrochemistry_import.owl>)' > $(IMPORTDIR)/emmo-electrochemistry_import.ofn; \
		$(ROBOT) convert -i $(IMPORTDIR)/emmo-electrochemistry_import.ofn -o $(IMPORTDIR)/emmo-electrochemistry_import.owl; \
		rm -f $(IMPORTDIR)/emmo-electrochemistry_import.ofn; \
	else \
		$(ROBOT) annotate --input $< --remove-annotations \
			 odk:normalize --add-source true \
			 extract --term-file $(IMPORTDIR)/emmo-electrochemistry_terms.txt $(T_IMPORTSEED) \
			         --force true --copy-ontology-annotations true \
			         --individuals include \
			         --method BOT \
			 remove $(foreach p, $(ANNOTATION_PROPERTIES), --term $(p)) \
			        --term-file $(IMPORTDIR)/emmo-electrochemistry_terms.txt $(T_IMPORTSEED) \
			        --select complement --select annotation-properties \
			 odk:normalize --base-iri http://purl.obolibrary.org/obo \
			               --subset-decls true --synonym-decls true \
			 repair --merge-axiom-annotations true \
			 $(ANNOTATE_CONVERT_FILE); \
	fi

QUDT_SCHEMA_CACHE := ../../../cache/sources/qudt-schema.ttl
QUDT_SCHEMA_URL := http://qudt.org/2.1/schema/qudt
QUDT_SCHEMA_REQUIRED := true

.PHONY: mirror-qudt-schema
.PRECIOUS: $(MIRRORDIR)/qudt-schema.owl
mirror-qudt-schema: | $(TMPDIR)
	@if [ -f $(QUDT_SCHEMA_CACHE) ]; then \
		echo "Using local cache for qudt-schema: $(QUDT_SCHEMA_CACHE)"; \
		$(ROBOT) convert -i $(QUDT_SCHEMA_CACHE) -o $(TMPDIR)/$@.owl; \
	elif [ -n "$(QUDT_SCHEMA_URL)" ]; then \
		echo "Downloading qudt-schema from $(QUDT_SCHEMA_URL)"; \
		if curl -L "$(QUDT_SCHEMA_URL)" -H "Accept: application/rdf+xml, application/owl+xml;q=0.95, text/turtle;q=0.9, text/plain;q=0.8, text/xml;q=0.8" --create-dirs -o $(TMPDIR)/qudt-schema-download.owl --retry 4 --max-time 200 && $(ROBOT) convert -i $(TMPDIR)/qudt-schema-download.owl -o $(TMPDIR)/$@.owl; then \
			true; \
		else \
			echo "Remote fetch failed for qudt-schema; writing placeholder mirror for shadow-mode continuity."; \
			printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/qudt-schema_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/qudt-schema_import.owl>)' > $(TMPDIR)/$@.ofn; \
			$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
		fi; \
	elif [ "$(QUDT_SCHEMA_REQUIRED)" = "true" ]; then \
		echo "Missing required cache or remote URL for qudt-schema; writing placeholder mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/qudt-schema_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/qudt-schema_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	else \
		echo "Skipping optional source qudt-schema; writing placeholder import mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/qudt-schema_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/qudt-schema_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	fi

$(IMPORTDIR)/qudt-schema_import.owl: $(MIRRORDIR)/qudt-schema.owl $(IMPORTDIR)/qudt-schema_terms.txt $(IMPORTSEED) | all_robot_plugins
	@if [ ! -s $(IMPORTDIR)/qudt-schema_terms.txt ]; then \
		echo "No configured terms for qudt-schema; writing placeholder import module."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/qudt-schema_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/qudt-schema_import.owl>)' > $(IMPORTDIR)/qudt-schema_import.ofn; \
		$(ROBOT) convert -i $(IMPORTDIR)/qudt-schema_import.ofn -o $(IMPORTDIR)/qudt-schema_import.owl; \
		rm -f $(IMPORTDIR)/qudt-schema_import.ofn; \
	else \
		$(ROBOT) annotate --input $< --remove-annotations \
			 odk:normalize --add-source true \
			 extract --term-file $(IMPORTDIR)/qudt-schema_terms.txt $(T_IMPORTSEED) \
			         --force true --copy-ontology-annotations true \
			         --individuals include \
			         --method BOT \
			 remove $(foreach p, $(ANNOTATION_PROPERTIES), --term $(p)) \
			        --term-file $(IMPORTDIR)/qudt-schema_terms.txt $(T_IMPORTSEED) \
			        --select complement --select annotation-properties \
			 odk:normalize --base-iri http://purl.obolibrary.org/obo \
			               --subset-decls true --synonym-decls true \
			 repair --merge-axiom-annotations true \
			 $(ANNOTATE_CONVERT_FILE); \
	fi

QUDT_UNITS_CACHE := ../../../cache/sources/qudt-units.ttl
QUDT_UNITS_URL := http://qudt.org/2.1/vocab/unit
QUDT_UNITS_REQUIRED := true

.PHONY: mirror-qudt-units
.PRECIOUS: $(MIRRORDIR)/qudt-units.owl
mirror-qudt-units: | $(TMPDIR)
	@if [ -f $(QUDT_UNITS_CACHE) ]; then \
		echo "Using local cache for qudt-units: $(QUDT_UNITS_CACHE)"; \
		$(ROBOT) convert -i $(QUDT_UNITS_CACHE) -o $(TMPDIR)/$@.owl; \
	elif [ -n "$(QUDT_UNITS_URL)" ]; then \
		echo "Downloading qudt-units from $(QUDT_UNITS_URL)"; \
		if curl -L "$(QUDT_UNITS_URL)" -H "Accept: application/rdf+xml, application/owl+xml;q=0.95, text/turtle;q=0.9, text/plain;q=0.8, text/xml;q=0.8" --create-dirs -o $(TMPDIR)/qudt-units-download.owl --retry 4 --max-time 200 && $(ROBOT) convert -i $(TMPDIR)/qudt-units-download.owl -o $(TMPDIR)/$@.owl; then \
			true; \
		else \
			echo "Remote fetch failed for qudt-units; writing placeholder mirror for shadow-mode continuity."; \
			printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/qudt-units_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/qudt-units_import.owl>)' > $(TMPDIR)/$@.ofn; \
			$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
		fi; \
	elif [ "$(QUDT_UNITS_REQUIRED)" = "true" ]; then \
		echo "Missing required cache or remote URL for qudt-units; writing placeholder mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/qudt-units_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/qudt-units_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	else \
		echo "Skipping optional source qudt-units; writing placeholder import mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/qudt-units_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/qudt-units_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	fi

$(IMPORTDIR)/qudt-units_import.owl: $(MIRRORDIR)/qudt-units.owl $(IMPORTDIR)/qudt-units_terms.txt $(IMPORTSEED) | all_robot_plugins
	@if [ ! -s $(IMPORTDIR)/qudt-units_terms.txt ]; then \
		echo "No configured terms for qudt-units; writing placeholder import module."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/qudt-units_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/qudt-units_import.owl>)' > $(IMPORTDIR)/qudt-units_import.ofn; \
		$(ROBOT) convert -i $(IMPORTDIR)/qudt-units_import.ofn -o $(IMPORTDIR)/qudt-units_import.owl; \
		rm -f $(IMPORTDIR)/qudt-units_import.ofn; \
	else \
		$(ROBOT) annotate --input $< --remove-annotations \
			 odk:normalize --add-source true \
			 extract --term-file $(IMPORTDIR)/qudt-units_terms.txt $(T_IMPORTSEED) \
			         --force true --copy-ontology-annotations true \
			         --individuals include \
			         --method BOT \
			 remove $(foreach p, $(ANNOTATION_PROPERTIES), --term $(p)) \
			        --term-file $(IMPORTDIR)/qudt-units_terms.txt $(T_IMPORTSEED) \
			        --select complement --select annotation-properties \
			 odk:normalize --base-iri http://purl.obolibrary.org/obo \
			               --subset-decls true --synonym-decls true \
			 repair --merge-axiom-annotations true \
			 $(ANNOTATE_CONVERT_FILE); \
	fi

QUDT_QUANTITYKINDS_CACHE := ../../../cache/sources/qudt-quantitykinds.ttl
QUDT_QUANTITYKINDS_URL := http://qudt.org/2.1/vocab/quantitykind
QUDT_QUANTITYKINDS_REQUIRED := true

.PHONY: mirror-qudt-quantitykinds
.PRECIOUS: $(MIRRORDIR)/qudt-quantitykinds.owl
mirror-qudt-quantitykinds: | $(TMPDIR)
	@if [ -f $(QUDT_QUANTITYKINDS_CACHE) ]; then \
		echo "Using local cache for qudt-quantitykinds: $(QUDT_QUANTITYKINDS_CACHE)"; \
		$(ROBOT) convert -i $(QUDT_QUANTITYKINDS_CACHE) -o $(TMPDIR)/$@.owl; \
	elif [ -n "$(QUDT_QUANTITYKINDS_URL)" ]; then \
		echo "Downloading qudt-quantitykinds from $(QUDT_QUANTITYKINDS_URL)"; \
		if curl -L "$(QUDT_QUANTITYKINDS_URL)" -H "Accept: application/rdf+xml, application/owl+xml;q=0.95, text/turtle;q=0.9, text/plain;q=0.8, text/xml;q=0.8" --create-dirs -o $(TMPDIR)/qudt-quantitykinds-download.owl --retry 4 --max-time 200 && $(ROBOT) convert -i $(TMPDIR)/qudt-quantitykinds-download.owl -o $(TMPDIR)/$@.owl; then \
			true; \
		else \
			echo "Remote fetch failed for qudt-quantitykinds; writing placeholder mirror for shadow-mode continuity."; \
			printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/qudt-quantitykinds_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/qudt-quantitykinds_import.owl>)' > $(TMPDIR)/$@.ofn; \
			$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
		fi; \
	elif [ "$(QUDT_QUANTITYKINDS_REQUIRED)" = "true" ]; then \
		echo "Missing required cache or remote URL for qudt-quantitykinds; writing placeholder mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/qudt-quantitykinds_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/qudt-quantitykinds_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	else \
		echo "Skipping optional source qudt-quantitykinds; writing placeholder import mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/qudt-quantitykinds_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/qudt-quantitykinds_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	fi

$(IMPORTDIR)/qudt-quantitykinds_import.owl: $(MIRRORDIR)/qudt-quantitykinds.owl $(IMPORTDIR)/qudt-quantitykinds_terms.txt $(IMPORTSEED) | all_robot_plugins
	@if [ ! -s $(IMPORTDIR)/qudt-quantitykinds_terms.txt ]; then \
		echo "No configured terms for qudt-quantitykinds; writing placeholder import module."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/qudt-quantitykinds_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/qudt-quantitykinds_import.owl>)' > $(IMPORTDIR)/qudt-quantitykinds_import.ofn; \
		$(ROBOT) convert -i $(IMPORTDIR)/qudt-quantitykinds_import.ofn -o $(IMPORTDIR)/qudt-quantitykinds_import.owl; \
		rm -f $(IMPORTDIR)/qudt-quantitykinds_import.ofn; \
	else \
		$(ROBOT) annotate --input $< --remove-annotations \
			 odk:normalize --add-source true \
			 extract --term-file $(IMPORTDIR)/qudt-quantitykinds_terms.txt $(T_IMPORTSEED) \
			         --force true --copy-ontology-annotations true \
			         --individuals include \
			         --method BOT \
			 remove $(foreach p, $(ANNOTATION_PROPERTIES), --term $(p)) \
			        --term-file $(IMPORTDIR)/qudt-quantitykinds_terms.txt $(T_IMPORTSEED) \
			        --select complement --select annotation-properties \
			 odk:normalize --base-iri http://purl.obolibrary.org/obo \
			               --subset-decls true --synonym-decls true \
			 repair --merge-axiom-annotations true \
			 $(ANNOTATE_CONVERT_FILE); \
	fi

CHEBI_CACHE := ../../../cache/sources/chebi.tsv
CHEBI_URL := 
CHEBI_REQUIRED := false

.PHONY: mirror-chebi
.PRECIOUS: $(MIRRORDIR)/chebi.owl
mirror-chebi: | $(TMPDIR)
	@if [ -f $(CHEBI_CACHE) ]; then \
		echo "Using local cache for chebi: $(CHEBI_CACHE)"; \
		$(ROBOT) convert -i $(CHEBI_CACHE) -o $(TMPDIR)/$@.owl; \
	elif [ -n "$(CHEBI_URL)" ]; then \
		echo "Downloading chebi from $(CHEBI_URL)"; \
		if curl -L "$(CHEBI_URL)" -H "Accept: application/rdf+xml, application/owl+xml;q=0.95, text/turtle;q=0.9, text/plain;q=0.8, text/xml;q=0.8" --create-dirs -o $(TMPDIR)/chebi-download.owl --retry 4 --max-time 200 && $(ROBOT) convert -i $(TMPDIR)/chebi-download.owl -o $(TMPDIR)/$@.owl; then \
			true; \
		else \
			echo "Remote fetch failed for chebi; writing placeholder mirror for shadow-mode continuity."; \
			printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/chebi_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/chebi_import.owl>)' > $(TMPDIR)/$@.ofn; \
			$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
		fi; \
	elif [ "$(CHEBI_REQUIRED)" = "true" ]; then \
		echo "Missing required cache or remote URL for chebi; writing placeholder mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/chebi_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/chebi_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	else \
		echo "Skipping optional source chebi; writing placeholder import mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/chebi_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/chebi_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	fi

$(IMPORTDIR)/chebi_import.owl: $(MIRRORDIR)/chebi.owl $(IMPORTDIR)/chebi_terms.txt $(IMPORTSEED) | all_robot_plugins
	@if [ ! -s $(IMPORTDIR)/chebi_terms.txt ]; then \
		echo "No configured terms for chebi; writing placeholder import module."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/chebi_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/chebi_import.owl>)' > $(IMPORTDIR)/chebi_import.ofn; \
		$(ROBOT) convert -i $(IMPORTDIR)/chebi_import.ofn -o $(IMPORTDIR)/chebi_import.owl; \
		rm -f $(IMPORTDIR)/chebi_import.ofn; \
	else \
		$(ROBOT) annotate --input $< --remove-annotations \
			 odk:normalize --add-source true \
			 extract --term-file $(IMPORTDIR)/chebi_terms.txt $(T_IMPORTSEED) \
			         --force true --copy-ontology-annotations true \
			         --individuals include \
			         --method BOT \
			 remove $(foreach p, $(ANNOTATION_PROPERTIES), --term $(p)) \
			        --term-file $(IMPORTDIR)/chebi_terms.txt $(T_IMPORTSEED) \
			        --select complement --select annotation-properties \
			 odk:normalize --base-iri http://purl.obolibrary.org/obo \
			               --subset-decls true --synonym-decls true \
			 repair --merge-axiom-annotations true \
			 $(ANNOTATE_CONVERT_FILE); \
	fi

PROV_O_CACHE := ../../../cache/sources/prov-o.ttl
PROV_O_URL := https://www.w3.org/ns/prov-o
PROV_O_REQUIRED := true

.PHONY: mirror-prov-o
.PRECIOUS: $(MIRRORDIR)/prov-o.owl
mirror-prov-o: | $(TMPDIR)
	@if [ -f $(PROV_O_CACHE) ]; then \
		echo "Using local cache for prov-o: $(PROV_O_CACHE)"; \
		$(ROBOT) convert -i $(PROV_O_CACHE) -o $(TMPDIR)/$@.owl; \
	elif [ -n "$(PROV_O_URL)" ]; then \
		echo "Downloading prov-o from $(PROV_O_URL)"; \
		if curl -L "$(PROV_O_URL)" -H "Accept: application/rdf+xml, application/owl+xml;q=0.95, text/turtle;q=0.9, text/plain;q=0.8, text/xml;q=0.8" --create-dirs -o $(TMPDIR)/prov-o-download.owl --retry 4 --max-time 200 && $(ROBOT) convert -i $(TMPDIR)/prov-o-download.owl -o $(TMPDIR)/$@.owl; then \
			true; \
		else \
			echo "Remote fetch failed for prov-o; writing placeholder mirror for shadow-mode continuity."; \
			printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/prov-o_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/prov-o_import.owl>)' > $(TMPDIR)/$@.ofn; \
			$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
		fi; \
	elif [ "$(PROV_O_REQUIRED)" = "true" ]; then \
		echo "Missing required cache or remote URL for prov-o; writing placeholder mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/prov-o_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/prov-o_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	else \
		echo "Skipping optional source prov-o; writing placeholder import mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/prov-o_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/prov-o_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	fi

$(IMPORTDIR)/prov-o_import.owl: $(MIRRORDIR)/prov-o.owl $(IMPORTDIR)/prov-o_terms.txt $(IMPORTSEED) | all_robot_plugins
	@if [ ! -s $(IMPORTDIR)/prov-o_terms.txt ]; then \
		echo "No configured terms for prov-o; writing placeholder import module."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/prov-o_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/prov-o_import.owl>)' > $(IMPORTDIR)/prov-o_import.ofn; \
		$(ROBOT) convert -i $(IMPORTDIR)/prov-o_import.ofn -o $(IMPORTDIR)/prov-o_import.owl; \
		rm -f $(IMPORTDIR)/prov-o_import.ofn; \
	else \
		$(ROBOT) annotate --input $< --remove-annotations \
			 odk:normalize --add-source true \
			 extract --term-file $(IMPORTDIR)/prov-o_terms.txt $(T_IMPORTSEED) \
			         --force true --copy-ontology-annotations true \
			         --individuals include \
			         --method BOT \
			 remove $(foreach p, $(ANNOTATION_PROPERTIES), --term $(p)) \
			        --term-file $(IMPORTDIR)/prov-o_terms.txt $(T_IMPORTSEED) \
			        --select complement --select annotation-properties \
			 odk:normalize --base-iri http://purl.obolibrary.org/obo \
			               --subset-decls true --synonym-decls true \
			 repair --merge-axiom-annotations true \
			 $(ANNOTATE_CONVERT_FILE); \
	fi

DCTERMS_CACHE := ../../../cache/sources/dcterms.ttl
DCTERMS_URL := http://purl.org/dc/terms/
DCTERMS_REQUIRED := true

.PHONY: mirror-dcterms
.PRECIOUS: $(MIRRORDIR)/dcterms.owl
mirror-dcterms: | $(TMPDIR)
	@if [ -f $(DCTERMS_CACHE) ]; then \
		echo "Using local cache for dcterms: $(DCTERMS_CACHE)"; \
		$(ROBOT) convert -i $(DCTERMS_CACHE) -o $(TMPDIR)/$@.owl; \
	elif [ -n "$(DCTERMS_URL)" ]; then \
		echo "Downloading dcterms from $(DCTERMS_URL)"; \
		if curl -L "$(DCTERMS_URL)" -H "Accept: application/rdf+xml, application/owl+xml;q=0.95, text/turtle;q=0.9, text/plain;q=0.8, text/xml;q=0.8" --create-dirs -o $(TMPDIR)/dcterms-download.owl --retry 4 --max-time 200 && $(ROBOT) convert -i $(TMPDIR)/dcterms-download.owl -o $(TMPDIR)/$@.owl; then \
			true; \
		else \
			echo "Remote fetch failed for dcterms; writing placeholder mirror for shadow-mode continuity."; \
			printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/dcterms_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/dcterms_import.owl>)' > $(TMPDIR)/$@.ofn; \
			$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
		fi; \
	elif [ "$(DCTERMS_REQUIRED)" = "true" ]; then \
		echo "Missing required cache or remote URL for dcterms; writing placeholder mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/dcterms_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/dcterms_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	else \
		echo "Skipping optional source dcterms; writing placeholder import mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/dcterms_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/dcterms_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	fi

$(IMPORTDIR)/dcterms_import.owl: $(MIRRORDIR)/dcterms.owl $(IMPORTDIR)/dcterms_terms.txt $(IMPORTSEED) | all_robot_plugins
	@if [ ! -s $(IMPORTDIR)/dcterms_terms.txt ]; then \
		echo "No configured terms for dcterms; writing placeholder import module."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/dcterms_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/dcterms_import.owl>)' > $(IMPORTDIR)/dcterms_import.ofn; \
		$(ROBOT) convert -i $(IMPORTDIR)/dcterms_import.ofn -o $(IMPORTDIR)/dcterms_import.owl; \
		rm -f $(IMPORTDIR)/dcterms_import.ofn; \
	else \
		$(ROBOT) annotate --input $< --remove-annotations \
			 odk:normalize --add-source true \
			 extract --term-file $(IMPORTDIR)/dcterms_terms.txt $(T_IMPORTSEED) \
			         --force true --copy-ontology-annotations true \
			         --individuals include \
			         --method BOT \
			 remove $(foreach p, $(ANNOTATION_PROPERTIES), --term $(p)) \
			        --term-file $(IMPORTDIR)/dcterms_terms.txt $(T_IMPORTSEED) \
			        --select complement --select annotation-properties \
			 odk:normalize --base-iri http://purl.obolibrary.org/obo \
			               --subset-decls true --synonym-decls true \
			 repair --merge-axiom-annotations true \
			 $(ANNOTATE_CONVERT_FILE); \
	fi

VANN_CACHE := ../../../cache/sources/vann.ttl
VANN_URL := http://purl.org/vocab/vann/
VANN_REQUIRED := true

.PHONY: mirror-vann
.PRECIOUS: $(MIRRORDIR)/vann.owl
mirror-vann: | $(TMPDIR)
	@if [ -f $(VANN_CACHE) ]; then \
		echo "Using local cache for vann: $(VANN_CACHE)"; \
		$(ROBOT) convert -i $(VANN_CACHE) -o $(TMPDIR)/$@.owl; \
	elif [ -n "$(VANN_URL)" ]; then \
		echo "Downloading vann from $(VANN_URL)"; \
		if curl -L "$(VANN_URL)" -H "Accept: application/rdf+xml, application/owl+xml;q=0.95, text/turtle;q=0.9, text/plain;q=0.8, text/xml;q=0.8" --create-dirs -o $(TMPDIR)/vann-download.owl --retry 4 --max-time 200 && $(ROBOT) convert -i $(TMPDIR)/vann-download.owl -o $(TMPDIR)/$@.owl; then \
			true; \
		else \
			echo "Remote fetch failed for vann; writing placeholder mirror for shadow-mode continuity."; \
			printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/vann_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/vann_import.owl>)' > $(TMPDIR)/$@.ofn; \
			$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
		fi; \
	elif [ "$(VANN_REQUIRED)" = "true" ]; then \
		echo "Missing required cache or remote URL for vann; writing placeholder mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/vann_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/vann_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	else \
		echo "Skipping optional source vann; writing placeholder import mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/vann_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/vann_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	fi

$(IMPORTDIR)/vann_import.owl: $(MIRRORDIR)/vann.owl $(IMPORTDIR)/vann_terms.txt $(IMPORTSEED) | all_robot_plugins
	@if [ ! -s $(IMPORTDIR)/vann_terms.txt ]; then \
		echo "No configured terms for vann; writing placeholder import module."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/vann_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/vann_import.owl>)' > $(IMPORTDIR)/vann_import.ofn; \
		$(ROBOT) convert -i $(IMPORTDIR)/vann_import.ofn -o $(IMPORTDIR)/vann_import.owl; \
		rm -f $(IMPORTDIR)/vann_import.ofn; \
	else \
		$(ROBOT) annotate --input $< --remove-annotations \
			 odk:normalize --add-source true \
			 extract --term-file $(IMPORTDIR)/vann_terms.txt $(T_IMPORTSEED) \
			         --force true --copy-ontology-annotations true \
			         --individuals include \
			         --method BOT \
			 remove $(foreach p, $(ANNOTATION_PROPERTIES), --term $(p)) \
			        --term-file $(IMPORTDIR)/vann_terms.txt $(T_IMPORTSEED) \
			        --select complement --select annotation-properties \
			 odk:normalize --base-iri http://purl.obolibrary.org/obo \
			               --subset-decls true --synonym-decls true \
			 repair --merge-axiom-annotations true \
			 $(ANNOTATE_CONVERT_FILE); \
	fi

HDO_CACHE := ../../../cache/sources/hdo.owl
HDO_URL := https://purls.helmholtz-metadaten.de/hob/hdo.owl
HDO_REQUIRED := true

.PHONY: mirror-hdo
.PRECIOUS: $(MIRRORDIR)/hdo.owl
mirror-hdo: | $(TMPDIR)
	@if [ -f $(HDO_CACHE) ]; then \
		echo "Using local cache for hdo: $(HDO_CACHE)"; \
		$(ROBOT) convert -i $(HDO_CACHE) -o $(TMPDIR)/$@.owl; \
	elif [ -n "$(HDO_URL)" ]; then \
		echo "Downloading hdo from $(HDO_URL)"; \
		if curl -L "$(HDO_URL)" -H "Accept: application/rdf+xml, application/owl+xml;q=0.95, text/turtle;q=0.9, text/plain;q=0.8, text/xml;q=0.8" --create-dirs -o $(TMPDIR)/hdo-download.owl --retry 4 --max-time 200 && $(ROBOT) convert -i $(TMPDIR)/hdo-download.owl -o $(TMPDIR)/$@.owl; then \
			true; \
		else \
			echo "Remote fetch failed for hdo; writing placeholder mirror for shadow-mode continuity."; \
			printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/hdo_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/hdo_import.owl>)' > $(TMPDIR)/$@.ofn; \
			$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
		fi; \
	elif [ "$(HDO_REQUIRED)" = "true" ]; then \
		echo "Missing required cache or remote URL for hdo; writing placeholder mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/hdo_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/hdo_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	else \
		echo "Skipping optional source hdo; writing placeholder import mirror."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/hdo_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/hdo_import.owl>)' > $(TMPDIR)/$@.ofn; \
		$(ROBOT) convert -i $(TMPDIR)/$@.ofn -o $(TMPDIR)/$@.owl; \
	fi

$(IMPORTDIR)/hdo_import.owl: $(MIRRORDIR)/hdo.owl $(IMPORTDIR)/hdo_terms.txt $(IMPORTSEED) | all_robot_plugins
	@if [ ! -s $(IMPORTDIR)/hdo_terms.txt ]; then \
		echo "No configured terms for hdo; writing placeholder import module."; \
		printf '%s\n' 'Prefix(:=<http://purl.obolibrary.org/obo/h2kg/imports/hdo_import.owl>)' 'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)' '' 'Ontology(<http://purl.obolibrary.org/obo/h2kg/imports/hdo_import.owl>)' > $(IMPORTDIR)/hdo_import.ofn; \
		$(ROBOT) convert -i $(IMPORTDIR)/hdo_import.ofn -o $(IMPORTDIR)/hdo_import.owl; \
		rm -f $(IMPORTDIR)/hdo_import.ofn; \
	else \
		$(ROBOT) annotate --input $< --remove-annotations \
			 odk:normalize --add-source true \
			 extract --term-file $(IMPORTDIR)/hdo_terms.txt $(T_IMPORTSEED) \
			         --force true --copy-ontology-annotations true \
			         --individuals include \
			         --method BOT \
			 remove $(foreach p, $(ANNOTATION_PROPERTIES), --term $(p)) \
			        --term-file $(IMPORTDIR)/hdo_terms.txt $(T_IMPORTSEED) \
			        --select complement --select annotation-properties \
			 odk:normalize --base-iri http://purl.obolibrary.org/obo \
			               --subset-decls true --synonym-decls true \
			 repair --merge-axiom-annotations true \
			 $(ANNOTATE_CONVERT_FILE); \
	fi

